from __future__ import annotations

import json
from collections.abc import Iterable
from pathlib import Path

from PySide6.QtWidgets import (
    QComboBox,
    QLabel,
    QLineEdit,
    QPushButton,
    QTableWidget,
    QTabWidget,
    QWidget,
)

LANGUAGES: tuple[tuple[str, str], ...] = (
    ("en", "English"),
    ("es", "Español"),
    ("fr", "Français"),
    ("de", "Deutsch"),
    ("it", "Italiano"),
    ("pt", "Português"),
    ("ja", "日本語"),
    ("zh", "中文"),
    ("ko", "한국어"),
)


class LanguageManager:
    """Whole-application UI localization without per-widget translation calls.

    Source English strings are captured automatically from the live Qt widget tree.
    Catalogs are ordinary JSON files generated by scripts/generate_i18n.py using
    the configured local Ollama model. Missing entries safely fall back to English.
    """

    def __init__(self, root: QWidget, catalog_dir: Path | None = None) -> None:
        self.root = root
        self.catalog_dir = catalog_dir or Path(__file__).with_name("translations")
        self.current_language = "en"
        self._catalog: dict[str, str] = {}
        self._capture_sources()

    @property
    def languages(self) -> tuple[tuple[str, str], ...]:
        return LANGUAGES

    def set_language(self, language: str) -> None:
        if language not in {code for code, _ in LANGUAGES}:
            raise ValueError(f"Unsupported UI language: {language}")
        self._capture_sources()
        self.current_language = language
        self._catalog = self._load_catalog(language)
        self.apply()

    def _load_catalog(self, language: str) -> dict[str, str]:
        if language == "en":
            return {}
        path = self.catalog_dir / f"ui_{language}.json"
        if not path.exists():
            return {}
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return {}
        return (
            {str(k): str(v) for k, v in payload.items()}
            if isinstance(payload, dict)
            else {}
        )

    def _capture_sources(self) -> None:
        for widget in self._widgets():
            self._capture_widget(widget)

    @staticmethod
    def _remember(widget: QWidget, property_name: str, value: str) -> str:
        if not widget.property(property_name):
            widget.setProperty(property_name, value)
        return str(widget.property(property_name))

    def _capture_widget(self, widget: QWidget) -> None:
        if isinstance(widget, (QLabel, QPushButton)):
            text = widget.text()
            if text:
                self._remember(widget, "_psi_i18n_text", text)
            tooltip = widget.toolTip()
            if tooltip:
                self._remember(widget, "_psi_i18n_tooltip", tooltip)
        if isinstance(widget, QLineEdit):
            placeholder = widget.placeholderText()
            if placeholder:
                self._remember(widget, "_psi_i18n_placeholder", placeholder)
        if isinstance(widget, QComboBox):
            sources = list(widget.property("_psi_i18n_items") or [])
            if len(sources) != widget.count():
                sources = [widget.itemText(i) for i in range(widget.count())]
                widget.setProperty("_psi_i18n_items", sources)
        if isinstance(widget, QTabWidget):
            sources = list(widget.property("_psi_i18n_tabs") or [])
            if len(sources) != widget.count():
                sources = [widget.tabText(i) for i in range(widget.count())]
                widget.setProperty("_psi_i18n_tabs", sources)
        if isinstance(widget, QTableWidget):
            headers = [
                widget.horizontalHeaderItem(i).text()
                if widget.horizontalHeaderItem(i)
                else ""
                for i in range(widget.columnCount())
            ]
            if headers:
                widget.setProperty("_psi_i18n_headers", headers)

    def _translate(self, source: str) -> str:
        return self._catalog.get(source, source)

    def apply(self) -> None:
        self._capture_sources()
        for widget in self._widgets():
            if isinstance(widget, (QLabel, QPushButton)):
                source = widget.property("_psi_i18n_text")
                if source:
                    widget.setText(self._translate(str(source)))
                source = widget.property("_psi_i18n_tooltip")
                if source:
                    widget.setToolTip(self._translate(str(source)))
            if isinstance(widget, QLineEdit):
                source = widget.property("_psi_i18n_placeholder")
                if source:
                    widget.setPlaceholderText(self._translate(str(source)))
            if isinstance(widget, QComboBox):
                sources = list(widget.property("_psi_i18n_items") or [])
                for i, source in enumerate(sources):
                    if i < widget.count():
                        widget.setItemText(i, self._translate(str(source)))
            if isinstance(widget, QTabWidget):
                sources = list(widget.property("_psi_i18n_tabs") or [])
                for i, source in enumerate(sources):
                    if i < widget.count():
                        widget.setTabText(i, self._translate(str(source)))
            if isinstance(widget, QTableWidget):
                headers = list(widget.property("_psi_i18n_headers") or [])
                for i, source in enumerate(headers):
                    if i < widget.columnCount() and source:
                        item = widget.horizontalHeaderItem(i)
                        if item:
                            item.setText(self._translate(str(source)))
        title = self.root.property("_psi_i18n_window_title")
        if title:
            self.root.setWindowTitle(self._translate(str(title)))

    def register_dynamic(self, widgets: Iterable[QWidget]) -> None:
        for widget in widgets:
            self._capture_widget(widget)
        self.apply()

    def _widgets(self) -> list[QWidget]:
        return [self.root, *self.root.findChildren(QWidget)]
